version: '3.1'

services:
  postgres:
    image: postgres:13.13-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: water_billing
    ports:
      - 5432:5432
    volumes:
      - ./.data:/var/lib/postgresql/data